
services:
  webapi:
    build:
      context: .
      dockerfile: src/EmployeesManagement.API/Dockerfile
    ports:
      - "8080:8080" 
      - "8081:8081"
    container_name: employeesmanagement-api-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    # restart: on-failure 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    container_name: sqlserver
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: